version: "3.4"

x-logging: &x-logging
  driver: json-file
  options:
    tag: "{{.Name}}"

services:
  db:
    container_name: dt-is-backend_db
    build: ./postgres
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    logging: *x-logging

  app:
    container_name: dt-is-backend_app
    build: ./src
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    volumes:
      - static_volume:/src/static/
    logging: *x-logging
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c '/wait && gunicorn -w 3 --bind :8000 config.wsgi:application'
    environment:
      WAIT_HOSTS: db:5432
      WAIT_HOSTS_TIMEOUT: 120

  nginx:
    container_name: dt-is-backend_nginx
    build: ./nginx
    restart: always
    ports:
      - ${PORT}:80
    depends_on:
      - app
    volumes:
      - static_volume:/src/static/
    logging: *x-logging

volumes:
  db_volume:
  static_volume:
